# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

msabe <- function(Test, Reference, m, sigma_W0, sig_level) {
    .Call(`_adaptIVPT_msabe`, Test, Reference, m, sigma_W0, sig_level)
}

prms <- function(n, r, sigma2_WT, sigma2_WR, logGMR, m, sigma_W0, sig_level, nsim, ncores) {
    .Call(`_adaptIVPT_prms`, n, r, sigma2_WT, sigma2_WR, logGMR, m, sigma_W0, sig_level, nsim, ncores)
}

reestimate_samplesize <- function(n_init, r, lGMR, S2_WR, alpha_level, m, sigma_W0, target_power, nmax, nsim, ncores) {
    .Call(`_adaptIVPT_reestimate_samplesize`, n_init, r, lGMR, S2_WR, alpha_level, m, sigma_W0, target_power, nmax, nsim, ncores)
}

