# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mycbind <- function(X, l) {
    .Call(`_adjSURVCI_mycbind`, X, l)
}

myrbind <- function(X, l) {
    .Call(`_adjSURVCI_myrbind`, X, l)
}

myColsums <- function(X) {
    .Call(`_adjSURVCI_myColsums`, X)
}

myRowsums <- function(X) {
    .Call(`_adjSURVCI_myRowsums`, X)
}

hhat <- function(g, S, zc, dl) {
    .Call(`_adjSURVCI_hhat`, g, S, zc, dl)
}

mybetaestCENSORING <- function(times, deltas, covariates, betas, rhos) {
    .Call(`_adjSURVCI_mybetaestCENSORING`, times, deltas, covariates, betas, rhos)
}

betaestCOX <- function(times, causes, covariates, nobs, ncovs, cweight, betas) {
    .Call(`_adjSURVCI_betaestCOX`, times, causes, covariates, nobs, ncovs, cweight, betas)
}

betaestKM <- function(times, causes, covariates, nobs, ncovs, cweight, betas) {
    .Call(`_adjSURVCI_betaestKM`, times, causes, covariates, nobs, ncovs, cweight, betas)
}

mylambdaestCENSORING <- function(times, deltas, covariates, betas, rhos) {
    .Call(`_adjSURVCI_mylambdaestCENSORING`, times, deltas, covariates, betas, rhos)
}

se_beta_lambda_strata_COX_diff <- function(times, causes, covariates, cencovariates, nobs, ntotal, ncovs, cweight, betas, gammas, cluster, allcluster, nc, totalnc, expg, iIc, iI, idxtlambda, etapsi, ntotalobs, allcovariates, Zpred) {
    .Call(`_adjSURVCI_se_beta_lambda_strata_COX_diff`, times, causes, covariates, cencovariates, nobs, ntotal, ncovs, cweight, betas, gammas, cluster, allcluster, nc, totalnc, expg, iIc, iI, idxtlambda, etapsi, ntotalobs, allcovariates, Zpred)
}

se_beta_lambda_strata_COX_diff1 <- function(times, causes, covariates, cencovariates, nobs, nobs1, ncovs, cweight, betas, gammas, cluster, allcluster, nc, totalnc, expg, iIc, iI, idxtlambda, etapsi, zcminusecold, dMc1, ntotalobs, allcovariates) {
    .Call(`_adjSURVCI_se_beta_lambda_strata_COX_diff1`, times, causes, covariates, cencovariates, nobs, nobs1, ncovs, cweight, betas, gammas, cluster, allcluster, nc, totalnc, expg, iIc, iI, idxtlambda, etapsi, zcminusecold, dMc1, ntotalobs, allcovariates)
}

se_beta_lambda_strata_COX_diff_unstratified <- function(times, causes, covariates, cencovariates, nobs, ntotal, ncovs, cweight, betas, gammas, cluster, allcluster, nc, totalnc, expg, iIc, iI, idxtlambda, etapsi, ntotalobs, allcovariates, adjustedbetas, Zpred) {
    .Call(`_adjSURVCI_se_beta_lambda_strata_COX_diff_unstratified`, times, causes, covariates, cencovariates, nobs, ntotal, ncovs, cweight, betas, gammas, cluster, allcluster, nc, totalnc, expg, iIc, iI, idxtlambda, etapsi, ntotalobs, allcovariates, adjustedbetas, Zpred)
}

se_beta_lambda_strata_KM_diff <- function(times, causes, covariates, nobs, ntotal, ncovs, cweight, betas, cluster, allcluster, nc, totalnc, iI, idxtlambda, etapsi, ntotalobs, allcovariates, Zpred) {
    .Call(`_adjSURVCI_se_beta_lambda_strata_KM_diff`, times, causes, covariates, nobs, ntotal, ncovs, cweight, betas, cluster, allcluster, nc, totalnc, iI, idxtlambda, etapsi, ntotalobs, allcovariates, Zpred)
}

se_beta_lambda_strata_KM_diff_unstratified <- function(times, causes, covariates, nobs, ntotal, ncovs, cweight, betas, cluster, allcluster, nc, totalnc, iI, idxtlambda, etapsi, ntotalobs, adjustedcovariates, adjustedbetas, Zpred) {
    .Call(`_adjSURVCI_se_beta_lambda_strata_KM_diff_unstratified`, times, causes, covariates, nobs, ntotal, ncovs, cweight, betas, cluster, allcluster, nc, totalnc, iI, idxtlambda, etapsi, ntotalobs, adjustedcovariates, adjustedbetas, Zpred)
}

se_beta_strata_COX <- function(times, causes, covariates, cencovariates, nobs, ncovs, cweight, betas, gammas, nc, expg, iIc) {
    .Call(`_adjSURVCI_se_beta_strata_COX`, times, causes, covariates, cencovariates, nobs, ncovs, cweight, betas, gammas, nc, expg, iIc)
}

se_beta_strata_COX1 <- function(times, causes, covariates, cencovariates, nobs, nobs1, ncovs, cweight, betas, gammas, nc, expg, iIc, zcminusecold, totalnc, dMC1) {
    .Call(`_adjSURVCI_se_beta_strata_COX1`, times, causes, covariates, cencovariates, nobs, nobs1, ncovs, cweight, betas, gammas, nc, expg, iIc, zcminusecold, totalnc, dMC1)
}

se_beta_strata_KM <- function(times, causes, covariates, nobs, ncovs, cweight, betas, nc) {
    .Call(`_adjSURVCI_se_beta_strata_KM`, times, causes, covariates, nobs, ncovs, cweight, betas, nc)
}

se_beta_strata_COX_survival <- function(times, causes, covariates, nobs, ncovs, betas, nc, iI) {
    .Call(`_adjSURVCI_se_beta_strata_COX_survival`, times, causes, covariates, nobs, ncovs, betas, nc, iI)
}

se_lambda_strata_COX <- function(times, causes, covariates, nobs, ncovs, betas, nc, iI, idxtlambda, nctotal, etai, totalclusters) {
    .Call(`_adjSURVCI_se_lambda_strata_COX`, times, causes, covariates, nobs, ncovs, betas, nc, iI, idxtlambda, nctotal, etai, totalclusters)
}

se_adjusted_strata_COX <- function(times, causes, covariates, nobs, ncovs, betas, nc, iI, idxtlambda, nctotal, etai, totalclusters, newlambda, allcovariates, betasadjusted, Zpred) {
    .Call(`_adjSURVCI_se_adjusted_strata_COX`, times, causes, covariates, nobs, ncovs, betas, nc, iI, idxtlambda, nctotal, etai, totalclusters, newlambda, allcovariates, betasadjusted, Zpred)
}

mybetaestCOX <- function(times, deltas, covariates, betas) {
    .Call(`_adjSURVCI_mybetaestCOX`, times, deltas, covariates, betas)
}

