// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// project3
List project3(Nullable<RObject> mpms, Nullable<RObject> vrms, Nullable<RObject> stageframes, Nullable<RObject> supplements, Nullable<RObject> equivalence, Nullable<RObject> starts, Nullable<RObject> years, Nullable<RObject> patches, Nullable<RObject> tweights, Nullable<RObject> format, Nullable<RObject> entry_time, Nullable<RObject> sp_density, Nullable<RObject> ind_terms, Nullable<RObject> dev_terms, Nullable<RObject> fb_sparse, Nullable<RObject> firstage, Nullable<RObject> finalage, Nullable<RObject> fecage_min, Nullable<RObject> fecage_max, Nullable<RObject> cont, Nullable<RObject> fecmod, Nullable<RObject> density, Nullable<RObject> density_vr, Nullable<RObject> err_check, bool stochastic, bool integeronly, int substoch, int nreps, int times, int prep_mats, bool force_fb, double exp_tol, double theta_tol);
RcppExport SEXP _adapt3_project3(SEXP mpmsSEXP, SEXP vrmsSEXP, SEXP stageframesSEXP, SEXP supplementsSEXP, SEXP equivalenceSEXP, SEXP startsSEXP, SEXP yearsSEXP, SEXP patchesSEXP, SEXP tweightsSEXP, SEXP formatSEXP, SEXP entry_timeSEXP, SEXP sp_densitySEXP, SEXP ind_termsSEXP, SEXP dev_termsSEXP, SEXP fb_sparseSEXP, SEXP firstageSEXP, SEXP finalageSEXP, SEXP fecage_minSEXP, SEXP fecage_maxSEXP, SEXP contSEXP, SEXP fecmodSEXP, SEXP densitySEXP, SEXP density_vrSEXP, SEXP err_checkSEXP, SEXP stochasticSEXP, SEXP integeronlySEXP, SEXP substochSEXP, SEXP nrepsSEXP, SEXP timesSEXP, SEXP prep_matsSEXP, SEXP force_fbSEXP, SEXP exp_tolSEXP, SEXP theta_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Nullable<RObject> >::type mpms(mpmsSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type vrms(vrmsSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type stageframes(stageframesSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type supplements(supplementsSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type equivalence(equivalenceSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type starts(startsSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type years(yearsSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type patches(patchesSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type tweights(tweightsSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type format(formatSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type entry_time(entry_timeSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type sp_density(sp_densitySEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type ind_terms(ind_termsSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type dev_terms(dev_termsSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type fb_sparse(fb_sparseSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type firstage(firstageSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type finalage(finalageSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type fecage_min(fecage_minSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type fecage_max(fecage_maxSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type cont(contSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type fecmod(fecmodSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type density(densitySEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type density_vr(density_vrSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type err_check(err_checkSEXP);
    Rcpp::traits::input_parameter< bool >::type stochastic(stochasticSEXP);
    Rcpp::traits::input_parameter< bool >::type integeronly(integeronlySEXP);
    Rcpp::traits::input_parameter< int >::type substoch(substochSEXP);
    Rcpp::traits::input_parameter< int >::type nreps(nrepsSEXP);
    Rcpp::traits::input_parameter< int >::type times(timesSEXP);
    Rcpp::traits::input_parameter< int >::type prep_mats(prep_matsSEXP);
    Rcpp::traits::input_parameter< bool >::type force_fb(force_fbSEXP);
    Rcpp::traits::input_parameter< double >::type exp_tol(exp_tolSEXP);
    Rcpp::traits::input_parameter< double >::type theta_tol(theta_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(project3(mpms, vrms, stageframes, supplements, equivalence, starts, years, patches, tweights, format, entry_time, sp_density, ind_terms, dev_terms, fb_sparse, firstage, finalage, fecage_min, fecage_max, cont, fecmod, density, density_vr, err_check, stochastic, integeronly, substoch, nreps, times, prep_mats, force_fb, exp_tol, theta_tol));
    return rcpp_result_gen;
END_RCPP
}
// invade3
List invade3(Nullable<RObject> axis, Nullable<RObject> mpm, Nullable<RObject> vrm, Nullable<RObject> stageframe, Nullable<RObject> supplement, Nullable<RObject> equivalence, Nullable<RObject> starts, Nullable<RObject> years, Nullable<RObject> patches, Nullable<RObject> tweights, Nullable<RObject> format, Nullable<RObject> entry_time, Nullable<RObject> sp_density, Nullable<RObject> ind_terms, Nullable<RObject> dev_terms, Nullable<RObject> fb_sparse, Nullable<RObject> firstage, Nullable<RObject> finalage, Nullable<RObject> fecage_min, Nullable<RObject> fecage_max, Nullable<RObject> cont, Nullable<RObject> prebreeding, Nullable<RObject> fecmod, Nullable<RObject> density, Nullable<RObject> density_vr, Nullable<RObject> stochastic, Nullable<RObject> A_only, Nullable<RObject> integeronly, Nullable<RObject> fitness_table, Nullable<RObject> trait_optima, Nullable<RObject> zap_min, Nullable<RObject> converged_only, Nullable<RObject> err_check, int var_per_run, int substoch, double elast_mult, int nreps, int times, int fitness_times, double exp_tol, double theta_tol, double threshold, int loop_max);
RcppExport SEXP _adapt3_invade3(SEXP axisSEXP, SEXP mpmSEXP, SEXP vrmSEXP, SEXP stageframeSEXP, SEXP supplementSEXP, SEXP equivalenceSEXP, SEXP startsSEXP, SEXP yearsSEXP, SEXP patchesSEXP, SEXP tweightsSEXP, SEXP formatSEXP, SEXP entry_timeSEXP, SEXP sp_densitySEXP, SEXP ind_termsSEXP, SEXP dev_termsSEXP, SEXP fb_sparseSEXP, SEXP firstageSEXP, SEXP finalageSEXP, SEXP fecage_minSEXP, SEXP fecage_maxSEXP, SEXP contSEXP, SEXP prebreedingSEXP, SEXP fecmodSEXP, SEXP densitySEXP, SEXP density_vrSEXP, SEXP stochasticSEXP, SEXP A_onlySEXP, SEXP integeronlySEXP, SEXP fitness_tableSEXP, SEXP trait_optimaSEXP, SEXP zap_minSEXP, SEXP converged_onlySEXP, SEXP err_checkSEXP, SEXP var_per_runSEXP, SEXP substochSEXP, SEXP elast_multSEXP, SEXP nrepsSEXP, SEXP timesSEXP, SEXP fitness_timesSEXP, SEXP exp_tolSEXP, SEXP theta_tolSEXP, SEXP thresholdSEXP, SEXP loop_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Nullable<RObject> >::type axis(axisSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type mpm(mpmSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type vrm(vrmSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type stageframe(stageframeSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type supplement(supplementSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type equivalence(equivalenceSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type starts(startsSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type years(yearsSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type patches(patchesSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type tweights(tweightsSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type format(formatSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type entry_time(entry_timeSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type sp_density(sp_densitySEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type ind_terms(ind_termsSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type dev_terms(dev_termsSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type fb_sparse(fb_sparseSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type firstage(firstageSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type finalage(finalageSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type fecage_min(fecage_minSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type fecage_max(fecage_maxSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type cont(contSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type prebreeding(prebreedingSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type fecmod(fecmodSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type density(densitySEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type density_vr(density_vrSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type stochastic(stochasticSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type A_only(A_onlySEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type integeronly(integeronlySEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type fitness_table(fitness_tableSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type trait_optima(trait_optimaSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type zap_min(zap_minSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type converged_only(converged_onlySEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type err_check(err_checkSEXP);
    Rcpp::traits::input_parameter< int >::type var_per_run(var_per_runSEXP);
    Rcpp::traits::input_parameter< int >::type substoch(substochSEXP);
    Rcpp::traits::input_parameter< double >::type elast_mult(elast_multSEXP);
    Rcpp::traits::input_parameter< int >::type nreps(nrepsSEXP);
    Rcpp::traits::input_parameter< int >::type times(timesSEXP);
    Rcpp::traits::input_parameter< int >::type fitness_times(fitness_timesSEXP);
    Rcpp::traits::input_parameter< double >::type exp_tol(exp_tolSEXP);
    Rcpp::traits::input_parameter< double >::type theta_tol(theta_tolSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type loop_max(loop_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(invade3(axis, mpm, vrm, stageframe, supplement, equivalence, starts, years, patches, tweights, format, entry_time, sp_density, ind_terms, dev_terms, fb_sparse, firstage, finalage, fecage_min, fecage_max, cont, prebreeding, fecmod, density, density_vr, stochastic, A_only, integeronly, fitness_table, trait_optima, zap_min, converged_only, err_check, var_per_run, substoch, elast_mult, nreps, times, fitness_times, exp_tol, theta_tol, threshold, loop_max));
    return rcpp_result_gen;
END_RCPP
}
// ta_skeleton
DataFrame ta_skeleton(int rows);
RcppExport SEXP _adapt3_ta_skeleton(SEXP rowsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type rows(rowsSEXP);
    rcpp_result_gen = Rcpp::wrap(ta_skeleton(rows));
    return rcpp_result_gen;
END_RCPP
}
// trait_axis
Rcpp::List trait_axis(Nullable<RObject> historical, Nullable<RObject> stagebased, Nullable<RObject> agebased, Nullable<RObject> stageframe, Nullable<RObject> stage3, Nullable<RObject> stage2, Nullable<RObject> stage1, Nullable<RObject> age3, Nullable<RObject> age2, Nullable<RObject> eststage3, Nullable<RObject> eststage2, Nullable<RObject> eststage1, Nullable<RObject> estage3, Nullable<RObject> estage2, Nullable<RObject> givenrate, Nullable<RObject> offset, Nullable<RObject> multiplier, Nullable<RObject> type, Nullable<RObject> type_t12, Nullable<RObject> surv_dev, Nullable<RObject> obs_dev, Nullable<RObject> size_dev, Nullable<RObject> sizeb_dev, Nullable<RObject> sizec_dev, Nullable<RObject> repst_dev, Nullable<RObject> fec_dev, Nullable<RObject> jsurv_dev, Nullable<RObject> jobs_dev, Nullable<RObject> jsize_dev, Nullable<RObject> jsizeb_dev, Nullable<RObject> jsizec_dev, Nullable<RObject> jrepst_dev, Nullable<RObject> jmatst_dev);
RcppExport SEXP _adapt3_trait_axis(SEXP historicalSEXP, SEXP stagebasedSEXP, SEXP agebasedSEXP, SEXP stageframeSEXP, SEXP stage3SEXP, SEXP stage2SEXP, SEXP stage1SEXP, SEXP age3SEXP, SEXP age2SEXP, SEXP eststage3SEXP, SEXP eststage2SEXP, SEXP eststage1SEXP, SEXP estage3SEXP, SEXP estage2SEXP, SEXP givenrateSEXP, SEXP offsetSEXP, SEXP multiplierSEXP, SEXP typeSEXP, SEXP type_t12SEXP, SEXP surv_devSEXP, SEXP obs_devSEXP, SEXP size_devSEXP, SEXP sizeb_devSEXP, SEXP sizec_devSEXP, SEXP repst_devSEXP, SEXP fec_devSEXP, SEXP jsurv_devSEXP, SEXP jobs_devSEXP, SEXP jsize_devSEXP, SEXP jsizeb_devSEXP, SEXP jsizec_devSEXP, SEXP jrepst_devSEXP, SEXP jmatst_devSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Nullable<RObject> >::type historical(historicalSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type stagebased(stagebasedSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type agebased(agebasedSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type stageframe(stageframeSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type stage3(stage3SEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type stage2(stage2SEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type stage1(stage1SEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type age3(age3SEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type age2(age2SEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type eststage3(eststage3SEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type eststage2(eststage2SEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type eststage1(eststage1SEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type estage3(estage3SEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type estage2(estage2SEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type givenrate(givenrateSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type multiplier(multiplierSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type type(typeSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type type_t12(type_t12SEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type surv_dev(surv_devSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type obs_dev(obs_devSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type size_dev(size_devSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type sizeb_dev(sizeb_devSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type sizec_dev(sizec_devSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type repst_dev(repst_devSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type fec_dev(fec_devSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type jsurv_dev(jsurv_devSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type jobs_dev(jobs_devSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type jsize_dev(jsize_devSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type jsizeb_dev(jsizeb_devSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type jsizec_dev(jsizec_devSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type jrepst_dev(jrepst_devSEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type jmatst_dev(jmatst_devSEXP);
    rcpp_result_gen = Rcpp::wrap(trait_axis(historical, stagebased, agebased, stageframe, stage3, stage2, stage1, age3, age2, eststage3, eststage2, eststage1, estage3, estage2, givenrate, offset, multiplier, type, type_t12, surv_dev, obs_dev, size_dev, sizeb_dev, sizec_dev, repst_dev, fec_dev, jsurv_dev, jobs_dev, jsize_dev, jsizeb_dev, jsizec_dev, jrepst_dev, jmatst_dev));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_adapt3_project3", (DL_FUNC) &_adapt3_project3, 33},
    {"_adapt3_invade3", (DL_FUNC) &_adapt3_invade3, 43},
    {"_adapt3_ta_skeleton", (DL_FUNC) &_adapt3_ta_skeleton, 1},
    {"_adapt3_trait_axis", (DL_FUNC) &_adapt3_trait_axis, 33},
    {NULL, NULL, 0}
};

RcppExport void R_init_adapt3(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
