// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rho_koenker
arma::vec rho_koenker(arma::vec x, double tau);
RcppExport SEXP _alqrfe_rho_koenker(SEXP xSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(rho_koenker(x, tau));
    return rcpp_result_gen;
END_RCPP
}
// loss_qr
double loss_qr(arma::vec beta, arma::mat x, arma::vec y, double tau, int N, int d);
RcppExport SEXP _alqrfe_loss_qr(SEXP betaSEXP, SEXP xSEXP, SEXP ySEXP, SEXP tauSEXP, SEXP NSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(loss_qr(beta, x, y, tau, N, d));
    return rcpp_result_gen;
END_RCPP
}
// loss_qrfe
double loss_qrfe(arma::vec theta, arma::mat x, arma::vec y, arma::mat z, double tau, int n, int d, int mm);
RcppExport SEXP _alqrfe_loss_qrfe(SEXP thetaSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP tauSEXP, SEXP nSEXP, SEXP dSEXP, SEXP mmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type mm(mmSEXP);
    rcpp_result_gen = Rcpp::wrap(loss_qrfe(theta, x, y, z, tau, n, d, mm));
    return rcpp_result_gen;
END_RCPP
}
// loss_lqr
double loss_lqr(arma::vec theta, arma::mat x, arma::vec y, arma::mat z, double tau, int n, int d, int mm, double lambda);
RcppExport SEXP _alqrfe_loss_lqr(SEXP thetaSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP tauSEXP, SEXP nSEXP, SEXP dSEXP, SEXP mmSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type mm(mmSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(loss_lqr(theta, x, y, z, tau, n, d, mm, lambda));
    return rcpp_result_gen;
END_RCPP
}
// loss_alqr
double loss_alqr(arma::vec theta, arma::mat x, arma::vec y, arma::mat z, double tau, int n, int d, int mm, double lambda, arma::vec w);
RcppExport SEXP _alqrfe_loss_alqr(SEXP thetaSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP tauSEXP, SEXP nSEXP, SEXP dSEXP, SEXP mmSEXP, SEXP lambdaSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type mm(mmSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(loss_alqr(theta, x, y, z, tau, n, d, mm, lambda, w));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_alqrfe_rho_koenker", (DL_FUNC) &_alqrfe_rho_koenker, 2},
    {"_alqrfe_loss_qr", (DL_FUNC) &_alqrfe_loss_qr, 6},
    {"_alqrfe_loss_qrfe", (DL_FUNC) &_alqrfe_loss_qrfe, 8},
    {"_alqrfe_loss_lqr", (DL_FUNC) &_alqrfe_loss_lqr, 9},
    {"_alqrfe_loss_alqr", (DL_FUNC) &_alqrfe_loss_alqr, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_alqrfe(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
