structure(list(url = "http://localhost:8080/alfresco/api/-default-/public/alfresco/versions/1/nodes/-root-/children", 
    status_code = 201L, headers = structure(list(server = "Apache-Coyote/1.1", 
        `cache-control` = "no-cache", expires = "Thu, 01 Jan 1970 00:00:00 GMT", 
        pragma = "no-cache", `content-type` = "application/json;charset=UTF-8", 
        `content-length` = "423", date = "Tue, 09 Jul 2019 03:36:21 GMT"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 201L, version = "HTTP/1.1", 
        headers = structure(list(server = "Apache-Coyote/1.1", 
            `cache-control` = "no-cache", expires = "Thu, 01 Jan 1970 00:00:00 GMT", 
            pragma = "no-cache", `content-type` = "application/json;charset=UTF-8", 
            `content-length` = "423", date = "Tue, 09 Jul 2019 03:36:21 GMT"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"entry\":{\"aspectNames\":[\"cm:auditable\"],\"createdAt\":\"2019-07-09T03:36:21.195+0000\",\"isFolder\":true,\"isFile\":false,\"createdByUser\":{\"id\":\"admin\",\"displayName\":\"Administrator\"},\"modifiedAt\":\"2019-07-09T03:36:21.195+0000\",\"modifiedByUser\":{\"id\":\"admin\",\"displayName\":\"Administrator\"},\"name\":\"test-alf-node\",\"id\":\"d5544997-acd2-4af5-87ba-13d7e0ffdb7a\",\"nodeType\":\"cm:folder\",\"parentId\":\"766db199-b973-43d5-8048-25d78b388e14\"}}"), 
    date = structure(1562643381, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 1e-06, 
    connect = 1e-06, pretransfer = 1e-06, starttransfer = 1e-06, 
    total = 0)), class = "response")
