// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// AddSlices_Rcpp
NumericVector AddSlices_Rcpp(NumericMatrix slicematrix);
RcppExport SEXP _ambit_AddSlices_Rcpp(SEXP slicematrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type slicematrix(slicematrixSEXP);
    rcpp_result_gen = Rcpp::wrap(AddSlices_Rcpp(slicematrix));
    return rcpp_result_gen;
END_RCPP
}
// AddWeightedSlices_Rcpp
NumericVector AddWeightedSlices_Rcpp(NumericMatrix slicematrix, NumericVector weightvector);
RcppExport SEXP _ambit_AddWeightedSlices_Rcpp(SEXP slicematrixSEXP, SEXP weightvectorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type slicematrix(slicematrixSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weightvector(weightvectorSEXP);
    rcpp_result_gen = Rcpp::wrap(AddWeightedSlices_Rcpp(slicematrix, weightvector));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ambit_AddSlices_Rcpp", (DL_FUNC) &_ambit_AddSlices_Rcpp, 1},
    {"_ambit_AddWeightedSlices_Rcpp", (DL_FUNC) &_ambit_AddWeightedSlices_Rcpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_ambit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
